### ISSUE TITLE
ImportError: cannot import name concatenate

### ISSUE THREAD

**Issue by doantientai** [orobix/retina-unet#40]
`Traceback (most recent call last):
  File "./src/retinaNN_training.py", line 15, in <module>
    from keras.layers import Input, concatenate, Conv2D, MaxPooling2D, UpSampling2D, Reshape, core, Dropout
ImportError: cannot import name concatenate`

I got this problem when running `python run_training.py`

**Comment by galiaxy** [comment]
Hi! I also got the same error, and I resolved it by upgrading tensorflow;
` pip install tensorflow --upgrade`
Hope this helps!

**Comment by AllBecomesGood** [comment]
I'm running into this issue because i have to use cuda8 and it only works with tensorflow-gpu 1.4.1, so concatenate cant be imported for some reason
